---
name: Build container images

on:
  push:
  pull_request:
    branches: [develop]
  merge_group:

jobs:
  build_containers:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Sample-Server
        uses: actions/checkout@v6.0.2
        with:
          path: Sample-Server
          submodules: recursive
          persist-credentials: false

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.7.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.12.0

      - name: Login to Container Registry
        uses: docker/login-action@v3.7.0
        with:
          registry: codeberg.org
          username: ${{ env.FORGEJO_ACTOR }}
          password: ${{ secrets.registry_token }}

      - name: Get Container Meta Data
        uses: docker/metadata-action@v5.10.0
        id: docker_meta
        with:
          images: "codeberg.org/${{ env.FORGEJO_REPOSITORY }}"
          flavor: |
            latest=true
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
      - name: Build and push
        uses: docker/build-push-action@v6.18.0
        with:
          file: "./Sample-Server/Dockerfile"
          context: ./Sample-Server
          platforms: linux/amd64, linux/arm64
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          build-args: |
            VERSION=${{ steps.docker_meta.outputs.version }}
          push: true
